In [1]:
# Addition of two 4 x 4 matrices
A = [[1, 2, 3, 4],
     [5, 6, 7, 8],
     [9, 10, 11, 12],
     [13, 14, 15, 16]]
B = [[17, 18, 19, 20],
     [21, 22, 23, 24],
     [25, 26, 27, 28],
     [29, 30, 31, 32]]
C = []
for i in range(4):
    row = []
    for j in range(4):
        row.append(A[i][j] + B[i][j])
    C.append(row)
print("First Matrix:")
for row in A:
    print(row)
print("Second Matrix:")
for row in B:
    print(row)
print("Addition of Matrices:")
for row in C:
    print(row)

First Matrix:
[1, 2, 3, 4]
[5, 6, 7, 8]
[9, 10, 11, 12]
[13, 14, 15, 16]
Second Matrix:
[17, 18, 19, 20]
[21, 22, 23, 24]
[25, 26, 27, 28]
[29, 30, 31, 32]
Addition of Matrices:
[18, 20, 22, 24]
[26, 28, 30, 32]
[34, 36, 38, 40]
[42, 44, 46, 48]


In [2]:
import numpy as np
# Create two 4 x 4 matrices
A = np.array([[1, 2, 3, 4],
              [5, 6, 7, 8],
              [9, 10, 11, 12],
              [13, 14, 15, 16]])
B = np.array([[17, 18, 19, 20],
              [21, 22, 23, 24],
              [25, 26, 27, 28],
              [29, 30, 31, 32]])
# Add the matrices
C = A + B
print("First Matrix:")
print(A)
print("Second Matrix:")
print(B)
print("Addition of Matrices:")
print(C)


First Matrix:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
Second Matrix:
[[17 18 19 20]
 [21 22 23 24]
 [25 26 27 28]
 [29 30 31 32]]
Addition of Matrices:
[[18 20 22 24]
 [26 28 30 32]
 [34 36 38 40]
 [42 44 46 48]]
